### ISSUE TITLE
[ReferenceError: fs is not defined]

### ISSUE THREAD

**Issue by xsmallbird** [Dragory/gulp-hash#11]
hello, may be you can lint your code by eslint, there are many style problem.

and

hash.manifest function design has a problem, why not *fs.readFileSync(dest + manifestPath, {encoding: 'utf8'});* in line 74.

**Comment by Dragory** [comment]
Oh yeah, I can see the style and undefined fs problem, I'll fix those right away, thanks!

But about the other thing, I'm not sure I follow. Where would dest come from? Currently it directly uses the path you give it. Can you elaborate on that one?

**Comment by xsmallbird** [comment]
I will try my best to describe it. (My English is not well! )

if i have be the follow code:
```javascript
gulp.src('./js/**/*.js')
    .pipe(hash())
    .pipe(gulp.dest('public/js'))
    .pipe(hash.manifest('assets.json'))
    .pipe(gulp.dest('public'));
```
the absolute path of  assets.json is *process.cwd() + '/public/assets.json'*

but in your code on line 75 has the follow code:
```javascript
var content = fs.readFileSync(manifestPath, {encoding: 'utf8'});
```
if the manifestPath value also is *assets.json* and gulp.dest is *public*, the manifestPath exact value is *process.cwd() + '/assets.json'*
but my expected value is *process.cwd() + '/public/assets.json'*

I don't know you can get my point.

**Comment by Dragory** [comment]
Thanks, I see your point. I don't think this is a concern. `gulp.dest('public')` will still save the file in `process.cwd() + '/public/assets.json'` because of the `'public'` parameter. Additionally, if the destination directory was to be added to manifestPath, gulp.dest('public') would result in `public/public/assets.json`.

However, if you still need to change the path of the manifest file itself (i.e. doing `gulp.dest('public')` is not enough for some reason), I recommend checking out [gulp-rename](https://www.npmjs.com/package/gulp-rename). Here's an untested example:

```javascript
gulp.src('js/**/*.js')
    .pipe(hash())
    .pipe(gulp.dest('public/js'))
    .pipe(hash.manifest('assets.json'))
    .pipe(rename(function(p) {
        // Add 'public' to dirname
        p.dirname += '/public';
    }))
    .pipe(gulp.dest('.'));
```

**Comment by Dragory** [comment]
(Not sure if you saw my earlier reply here, I deleted it after re-reading your comment!)

I see your point now. You can work around this by putting 'public/' directly into the manifest path:
```javascript
    .pipe(hash.manifest('public/assets.json'))
    .pipe(gulp.dest('.'))
```

However, setting the base dir for the file could be a useful feature as an additional parameter to `hash.manifest()`. I'll see what I can do, thanks!

**Comment by xsmallbird** [comment]
yes, i solve it as same as you say:

```javascript
    .pipe(hash.manifest('public/assets.json'))
    .pipe(gulp.dest('.'))
```

I think you can do better! thanks!
