### ISSUE TITLE
Keep getting same hashing values (even with different algorithms)

### ISSUE THREAD

**Issue by nealoke** [Dragory/gulp-hash#13]
Hi,

I tried various things but I keep getting the same hashing values when running the hash() task. Even when changing the algorithm to sha256 or sha512 I get the same value.. I checked my gulp task a few times but can't seem to resolve the issue.

Running the task 1, 2, 3, 4 times always gives me the same hashing values (even in the manifest)

`gulp.task('hashjs', ['bundlejs'], function() {
	gulp.src('../export/js/bundle.min.js')
	.pipe(hash())
	.pipe(gulp.dest('../export/js'))
	.pipe(hash.manifest('assets.json'))
	.pipe(gulp.dest('./hashmanifest'));
});`

**Comment by nealoke** [comment]
Tried to change the hashLength to 12, which appends another 4 characters/digits to the end of the previous result, but also is static after rerunning the task.

Also not that I tried to solve this by deleting the "manifest" file. The same result always comes back to me... aka (80b59014)

**Comment by nealoke** [comment]
Ok so a way to solve this is by using the "version" option on the hash(). But I think that it is more logical to create a new hash whenever this task is called right? Otherwise what is the point of having a hash if it doesn't give you a random hash every time? :/ 

What do you think @Dragory ?

**Comment by Dragory** [comment]
It actually hashes the file contents. That way if nothing changes, the hash stays the same. Are you sure this isn't what you're experiencing?

**Comment by nealoke** [comment]
Hi, I tested it a few times and you are right! :+1: Didn't know the file contents were being hashed :/ Also did you create a way to callback the manifest result in another task / function?

**Comment by Dragory** [comment]
Once you have called `hash.manifest()`, the file in the gulp stream is the manifest file, and you can access its contents like you normally would in a gulp plugin. This is, however, up to another plugin to do, and is a bit of a hassle to implement in the gulpfile itself.

I'm not sure about your use case, but if you need to rewrite the file names in e.g. your index file, take a look at [gulp-hash-references](https://www.npmjs.com/package/gulp-hash-references).

**Comment by nealoke** [comment]
I achieved it by calling a dynamic require (so in another gulp task) but I needed to delay it (setTimeout of a minimum of 2 seconds otherwise the manifest file was always empty. Works fine in this way though ;) Thanks for the help!
