### ISSUE TITLE
Can we have a diff hash whenever we run the gulp task?

### ISSUE THREAD

**Issue by srikanthchitla** [Dragory/gulp-hash#25]
I have one CSS file with the hash file name. I want to change the hash name every time when I run the gulp task.
Can we do that? 
If it is there, Kindly help me to how to do that.

Thanks
Srikanth Chitla.

**Comment by Dragory** [comment]
At the moment, this is not possible with gulp-hash. This is because the idea of the plugin is to only change the hash when the contents of the file change.

What's your use case for changing the hash every time? Maybe there's another solution here.
