### ISSUE TITLE
More flexible way to append to a manifest?

### ISSUE THREAD

**Issue by borissamardzija** [Dragory/gulp-hash#3]
Hello,

I really like your plugin and hashOptions and easy way to change manifestPath file are really nice, but I have some difficulties appending manifest file.

I have read your [example-gulpfile.js] (https://github.com/Dragory/gulp-hash/blob/master/example/example-gulpfile.js), but as I can see, it's not applicable in my case.

```js
gulp.task('css', function () {
	build.css.forEach(function(group){
		Object.getOwnPropertyNames(group).forEach(function(group_file_path, index, array) {
			var assets = group[group_file_path];

			gulp.src(assets)
				.pipe(concat(group_file_path))
				.pipe(hash(hashOptions))
				.pipe(gulp.dest('.'))
		});
	});
});
```

My JSON looks like

```
{
    "css": [
        {
            "css/app.css": [
                "css/a1.css",
                "css/a2.css",
            ]
        },
        {
            "css/app2.css": [
                "css/b1.css",
                "css/b2.css"
            ]
        }
    ]
}
```

I would like to write all manifest data to one file, but file gets overwritten at every iteration.

Do you have some ideas / suggestions how to do this nicely?

**Comment by Dragory** [comment]
Hey, just updating to say I'm not dead. I've been fairly busy for the past couple of months, but I'll work on this soon.

**Comment by Dragory** [comment]
The append option is now live on NPM (v2.1.1). I will close this issue once I've updated the docs.

**Comment by borissamardzija** [comment]
Nice, thanks for adding that in. Will test when I catch up some time.
