### ISSUE TITLE
FYI: NPM still on 2.0.4 version

### ISSUE THREAD

**Issue by eobeda** [Dragory/gulp-hash#5]
Just an FYI, that npmjs.com is still publishing your older 2.0.4 version and does not offer your great 2.1.0 version.

gulp-hash   mivir
A gulp plugin for cachebusting files by adding a hash to their name and/or content. Optionally writes a JSON file with mappings from the original filename to the renamed one.
1   v2.0.4
 cache,  cachebust,  cache bust,  gulpplugin

**Comment by Dragory** [comment]
Ah, you're right, I forgot about that, thanks. The reason is that I haven't written tests for the new functionality yet and therefore cannot guarantee it works. There are also some possible race conditions with the `appendToManifest` parameter when used with async tasks that I intend to fix.

**Comment by Dragory** [comment]
Fixed as of a001f127b4aeafc62fbcf253f965b57b99d13920
