### ISSUE TITLE
Option version

### ISSUE THREAD

**Issue by ai** [Dragory/gulp-hash#6]
We need some `version` options to use it in `md5(content + version)`, like it Rails does.

It is useful, for example, when you fix webserver headers and you need to reload all assets.

**Comment by ai** [comment]
Fixed in https://github.com/Dragory/gulp-hash/pull/7

@Dragory hope for sooon feedback, because we really need this fix soon :).

**Comment by Dragory** [comment]
Hey, thanks for the PR! I haven't personally used such an option but it does fit the scope of the project and I can see it being useful, so I'm merging it in. The only thing I'm changing is the default value, which I'm setting to an empty string to preserve previous output when the option is not set.

Thanks!

**Comment by ai** [comment]
Awesome. I am wating for release.
